### The following Script Contains:
#### 1. Import Libraries and Data¶
#### 2. Data Wrangling
#### 3. Data Splitting
#### 4. Build Keras Model
#### 5. Compiling and Running Model
#### 6. Create Confusion Matrix
#### 7. Retry Keras Model (Until Convergence)

### 1. Import Libraries and Data

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dropout
from keras.layers import LSTM
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

In [4]:
# Set display options to show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
# Create path
path = r'/Users/asadagha/Documents/CF Data Analytics/Machine Learning/Achievement 2/Data Sets'

In [6]:
# Import datasets
X = pd.read_csv(os.path.join(path, 'Prepared Data', 'weather_cleaned.csv'))
prediction = pd.read_csv(os.path.join(path, 'Original Data', 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'))

In [7]:
X.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_cloud_cover,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_pressure,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_humidity,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,8,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,1.018,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,0.98,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,8,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,1.018,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,0.62,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,7,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,1.018,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,0.69,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,8,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,1.018,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,0.98,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,7,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,1.018,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,0.96,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [8]:
X.shape

(22950, 135)

In [9]:
prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [10]:
prediction.shape

(22950, 16)

### 02. Data Wrangling

In [12]:
# Drop DATE column from prediction dataset
prediction.drop(columns = 'DATE', inplace = True)

In [13]:
prediction.shape

(22950, 15)

In [14]:
y = prediction

In [15]:
X.shape

(22950, 135)

In [16]:
# Turn X and y into arrays
X = np.array(X)
y = np.array(y)
X

array([[ 7.    ,  0.85  ,  1.018 , ...,  8.5   ,  6.    , 10.9   ],
       [ 6.    ,  0.84  ,  1.018 , ...,  8.9   ,  5.6   , 12.1   ],
       [ 8.    ,  0.9   ,  1.018 , ..., 10.5   ,  8.1   , 12.9   ],
       ...,
       [ 4.    ,  0.76  ,  1.0227, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.8   ,  1.0212, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.84  ,  1.0193, ..., 10.7   ,  7.9   , 13.5   ]])

In [17]:
# Reshape X
X = X.reshape(-1,15,9)

In [18]:
X.shape

(22950, 15, 9)

In [19]:
X

array([[[  7.    ,   0.85  ,   1.018 , ...,   6.5   ,   0.8   ,
          10.9   ],
        [  1.    ,   0.81  ,   1.0195, ...,   3.7   ,  -0.9   ,
           7.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.4   ,  -0.4   ,
           5.1   ],
        ...,
        [  4.    ,   0.73  ,   1.0304, ...,  -5.9   ,  -8.5   ,
          -3.2   ],
        [  5.    ,   0.98  ,   1.0114, ...,   4.2   ,   2.2   ,
           4.9   ],
        [  5.    ,   0.88  ,   1.0003, ...,   8.5   ,   6.    ,
          10.9   ]],

       [[  6.    ,   0.84  ,   1.018 , ...,   6.1   ,   3.3   ,
          10.1   ],
        [  6.    ,   0.84  ,   1.0172, ...,   2.9   ,   2.2   ,
           4.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.3   ,   1.4   ,
           3.1   ],
        ...,
        [  6.    ,   0.97  ,   1.0292, ...,  -9.5   , -10.5   ,
          -8.5   ],
        [  5.    ,   0.62  ,   1.0114, ...,   4.    ,   3.    ,
           5.    ],
        [  7.    ,   0.91  ,   1.0007, ...,   8.9   ,   5.6   ,
          12.1   ]],

       [[  8.    ,   0.9   ,   1.018 , ...,   8.5   ,   5.1   ,
           9.9   ],
        [  6.    ,   0.77  ,   1.0179, ...,   3.1   ,  -0.5   ,
           6.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.7   ,   1.7   ,
           5.3   ],
        ...,
        [  8.    ,   0.93  ,   1.032 , ...,  -9.5   , -10.    ,
          -8.9   ],
        [  5.    ,   0.69  ,   1.0114, ...,   2.4   ,   1.3   ,
           4.1   ],
        [  7.    ,   0.91  ,   1.0096, ...,  10.5   ,   8.1   ,
          12.9   ]],

       ...,

       [[  4.    ,   0.76  ,   1.0227, ...,  16.7   ,  13.1   ,
          22.4   ],
        [  2.    ,   0.68  ,   1.0278, ...,  13.4   ,   8.6   ,
          18.2   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.3   ,   2.1   ,
           4.5   ],
        [  5.    ,   0.85  ,   1.0059, ...,  13.1   ,  12.1   ,
          14.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.8   ,   1.0212, ...,  15.4   ,  11.6   ,
          21.1   ],
        [  1.    ,   0.68  ,   1.0238, ...,  15.    ,   9.1   ,
          20.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.4   ,   2.7   ,
           4.1   ],
        [  5.    ,   0.94  ,   1.016 , ...,   7.5   ,   5.1   ,
          12.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.84  ,   1.0193, ...,  13.5   ,   9.9   ,
          19.2   ],
        [  4.    ,   0.68  ,   1.0235, ...,  14.4   ,  10.4   ,
          18.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  4.    ,   0.84  ,   1.0263, ...,   1.7   ,   0.7   ,
           2.7   ],
        [  5.    ,   0.97  ,   1.0164, ...,   9.7   ,   5.    ,
          12.6   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]]])

In [20]:
y.shape

(22950, 15)

In [21]:
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### 3. Data Splitting

In [23]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [24]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212, 15)
(5738, 15, 9) (5738, 15)

### 4. Build Keras Model

In [26]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(MaxPooling1D())
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='tanh')) # Don't use relu here!

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 7, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 15)             │           975 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 35,215 (137.56 KB)

 Trainable params: 35,215 (137.56 KB)

 Non-trainable params: 0 (0.00 B)

### 5. Compiling and Running Model

In [29]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [30]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0632 - loss: 24.2392
Epoch 2/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0089 - loss: 24.6903
Epoch 3/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0180 - loss: 24.5322
Epoch 4/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0251 - loss: 24.8014
Epoch 5/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0218 - loss: 24.6581
Epoch 6/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0529 - loss: 24.7030
Epoch 7/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0759 - loss: 24.3757
Epoch 8/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0503 - loss: 25.5417
Epoch 9/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0582 - loss: 24.8068
Epoch 10/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0478 - loss: 24.1908
Epoch 11/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0188 - loss: 24.3231
Epoch 12/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0205 - loss: 24.5084
Epoch 13/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0236 - loss: 24.3496
Epoch 14/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0436 - loss: 24.8299
Epoch 15/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0793 - loss: 24.8243
Epoch 16/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0561 - loss: 24.5463
Epoch 17/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0501 - loss: 24.5794
Epoch 18/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0329 - loss: 24.7822
Epoch 19/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0184 - loss: 24.6257
Epoch 20/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0119 - loss: 24.9596
Epoch 21/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0094 - loss: 24.8468
Epoch 22/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0228 - loss: 24.7197
Epoch 23/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0323 - loss: 24.4901
Epoch 24/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0438 - loss: 24.1554
Epoch 25/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0481 - loss: 24.1506
Epoch 26/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0589 - loss: 24.2899
Epoch 27/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0546 - loss: 24.5570
Epoch 28/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0639 - loss: 24.3905
Epoch 29/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0639 - loss: 24.4831
Epoch 30/30
1076/1076 - 1s - 1ms/step - accuracy: 0.0363 - loss: 24.4733

### 6. Confusion Matrix Creation

In [32]:
# Define list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'

}

In [33]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [34]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step
Pred        BUDAPEST  MADRID  OSLO
True
BASEL            393     218  3071
BELGRADE           4       2  1086
BUDAPEST           2       0   212
DEBILT             0       0    82
DUSSELDORF         0       0    29
HEATHROW           0       0    82
KASSEL             0       0    11
LJUBLJANA          0       0    61
MAASTRICHT         0       0     9
MADRID            22       2   434
MUNCHENB           0       0     8
OSLO               0       0     5
STOCKHOLM          0       0     4
VALENTIA           0       0     1

In [35]:
epochs = 30
batch_size = 16
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) # Options: sigmoid, tanh, softmax, relu

In [36]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 14, 4)          │            76 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 14, 16)         │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,851 (7.23 KB)

 Trainable params: 1,851 (7.23 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [38]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 573us/step - accuracy: 0.1143 - loss: 809.5172
Epoch 2/30
1076/1076 - 0s - 359us/step - accuracy: 0.1253 - loss: 8057.5386
Epoch 3/30
1076/1076 - 0s - 358us/step - accuracy: 0.1222 - loss: 27050.9180
Epoch 4/30
1076/1076 - 0s - 358us/step - accuracy: 0.1214 - loss: 57381.4492
Epoch 5/30
1076/1076 - 0s - 359us/step - accuracy: 0.1300 - loss: 103047.4844
Epoch 6/30
1076/1076 - 0s - 374us/step - accuracy: 0.1261 - loss: 159456.7812
Epoch 7/30
1076/1076 - 0s - 374us/step - accuracy: 0.1319 - loss: 233014.4219
Epoch 8/30
1076/1076 - 0s - 358us/step - accuracy: 0.1319 - loss: 321551.1250
Epoch 9/30
1076/1076 - 0s - 357us/step - accuracy: 0.1323 - loss: 429149.6250
Epoch 10/30
1076/1076 - 0s - 359us/step - accuracy: 0.1352 - loss: 548659.1875
Epoch 11/30
1076/1076 - 0s - 358us/step - accuracy: 0.1380 - loss: 689208.1875
Epoch 12/30
1076/1076 - 0s - 358us/step - accuracy: 0.1344 - loss: 855012.8125
Epoch 13/30
1076/1076 - 0s - 356us/step - accuracy: 0.1333 - loss: 1042070.1875
Epoch 14/30
1076/1076 - 0s - 360us/step - accuracy: 0.1352 - loss: 1264977.8750
Epoch 15/30
1076/1076 - 0s - 359us/step - accuracy: 0.1331 - loss: 1491726.8750
Epoch 16/30
1076/1076 - 0s - 359us/step - accuracy: 0.1352 - loss: 1756408.8750
Epoch 17/30
1076/1076 - 0s - 358us/step - accuracy: 0.1328 - loss: 2030219.7500
Epoch 18/30
1076/1076 - 0s - 358us/step - accuracy: 0.1340 - loss: 2361076.2500
Epoch 19/30
1076/1076 - 0s - 358us/step - accuracy: 0.1348 - loss: 2730462.5000
Epoch 20/30
1076/1076 - 0s - 359us/step - accuracy: 0.1328 - loss: 3114190.0000
Epoch 21/30
1076/1076 - 0s - 358us/step - accuracy: 0.1313 - loss: 3521024.0000
Epoch 22/30
1076/1076 - 0s - 373us/step - accuracy: 0.1364 - loss: 4002547.2500
Epoch 23/30
1076/1076 - 0s - 361us/step - accuracy: 0.1351 - loss: 4489776.0000
Epoch 24/30
1076/1076 - 0s - 359us/step - accuracy: 0.1346 - loss: 5044323.5000
Epoch 25/30
1076/1076 - 0s - 358us/step - accuracy: 0.1355 - loss: 5605896.0000
Epoch 26/30
1076/1076 - 0s - 359us/step - accuracy: 0.1359 - loss: 6250059.5000
Epoch 27/30
1076/1076 - 0s - 359us/step - accuracy: 0.1344 - loss: 6927268.5000
Epoch 28/30
1076/1076 - 0s - 359us/step - accuracy: 0.1296 - loss: 7674563.0000
Epoch 29/30
1076/1076 - 0s - 360us/step - accuracy: 0.1369 - loss: 8434497.0000
Epoch 30/30
1076/1076 - 0s - 357us/step - accuracy: 0.1311 - loss: 9218494.0000

In [39]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [40]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 272us/step
Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  KASSEL  \
True
BASEL         135        14       244      38          37      1758      18
BELGRADE        0         0       119       1           0       569       0
BUDAPEST        0         0        16       0           0       135       0
DEBILT          0         0         0       0           0        60       0
DUSSELDORF      0         0         0       0           0        23       0
HEATHROW        0         0         2       0           0        64       0
KASSEL          0         0         1       0           0         7       0
LJUBLJANA       0         0         3       0           0        23       0
MAASTRICHT      0         0         1       0           0         4       0
MADRID          4         0         9       0           0       188       0
MUNCHENB        0         0         1       0           0         1       0
OSLO            0         0         0       0           0         3       0
STOCKHOLM       0         0         2       0           0         1       0
VALENTIA        0         0         0       0           0         1       0

Pred        LJUBLJANA  MAASTRICHT  MADRID  MUNCHENB  OSLO  SONNBLICK  \
True
BASEL               1          40     726       500   123          7
BELGRADE            0           0     326        54    23          0
BUDAPEST            0           0      53         5     5          0
DEBILT              0           0      10         4     8          0
DUSSELDORF          0           0       5         0     1          0
HEATHROW            0           0      14         0     2          0
KASSEL              0           0       2         0     1          0
LJUBLJANA           0           0      34         1     0          0
MAASTRICHT          0           0       2         2     0          0
MADRID              0           1     235        10    11          0
MUNCHENB            0           0       5         1     0          0
OSLO                0           0       1         0     1          0
STOCKHOLM           0           0       0         1     0          0
VALENTIA            0           0       0         0     0          0

Pred        STOCKHOLM  VALENTIA
True
BASEL              13        28
BELGRADE            0         0
BUDAPEST            0         0
DEBILT              0         0
DUSSELDORF          0         0
HEATHROW            0         0
KASSEL              0         0
LJUBLJANA           0         0
MAASTRICHT          0         0
MADRID              0         0
MUNCHENB            0         0
OSLO                0         0
STOCKHOLM           0         0
VALENTIA            0         0

Softmax didn’t give good results; let’s try tanh, sigmoid, and relu instead

### 7. Retry Keras Model (Until Convergence)

In [43]:
epochs = 30
batch_size = 16
n_hidden = 128

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='tanh')) # Options: sigmoid, tanh, softmax, relu

In [44]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 14, 128)        │         2,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 14, 16)         │         2,064 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,191 (24.18 KB)

 Trainable params: 6,191 (24.18 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [46]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 663us/step - accuracy: 0.0195 - loss: 30.9535
Epoch 2/30
1076/1076 - 0s - 434us/step - accuracy: 0.0791 - loss: 31.2583
Epoch 3/30
1076/1076 - 0s - 434us/step - accuracy: 0.3886 - loss: 26.4701
Epoch 4/30
1076/1076 - 0s - 431us/step - accuracy: 0.4117 - loss: 24.3682
Epoch 5/30
1076/1076 - 0s - 430us/step - accuracy: 0.4014 - loss: 24.7427
Epoch 6/30
1076/1076 - 0s - 429us/step - accuracy: 0.4014 - loss: 24.7437
Epoch 7/30
1076/1076 - 0s - 435us/step - accuracy: 0.4014 - loss: 24.7437
Epoch 8/30
1076/1076 - 0s - 441us/step - accuracy: 0.4014 - loss: 24.7437
Epoch 9/30
1076/1076 - 1s - 472us/step - accuracy: 0.4014 - loss: 24.7437
Epoch 10/30
1076/1076 - 0s - 441us/step - accuracy: 0.4014 - loss: 24.7437
Epoch 11/30
1076/1076 - 0s - 435us/step - accuracy: 0.4014 - loss: 24.7437
Epoch 12/30
1076/1076 - 0s - 460us/step - accuracy: 0.4015 - loss: 24.7437
Epoch 13/30
1076/1076 - 1s - 489us/step - accuracy: 0.4015 - loss: 24.7437
Epoch 14/30
1076/1076 - 0s - 439us/step - accuracy: 0.4015 - loss: 24.7437
Epoch 15/30
1076/1076 - 0s - 459us/step - accuracy: 0.4015 - loss: 24.7446
Epoch 16/30
1076/1076 - 0s - 433us/step - accuracy: 0.4016 - loss: 24.7474
Epoch 17/30
1076/1076 - 0s - 430us/step - accuracy: 0.4016 - loss: 24.7409
Epoch 18/30
1076/1076 - 0s - 433us/step - accuracy: 0.4011 - loss: 24.7502
Epoch 19/30
1076/1076 - 0s - 436us/step - accuracy: 0.4011 - loss: 24.7512
Epoch 20/30
1076/1076 - 0s - 431us/step - accuracy: 0.4011 - loss: 24.7512
Epoch 21/30
1076/1076 - 0s - 458us/step - accuracy: 0.4011 - loss: 24.7512
Epoch 22/30
1076/1076 - 0s - 433us/step - accuracy: 0.4011 - loss: 24.7512
Epoch 23/30
1076/1076 - 0s - 458us/step - accuracy: 0.4011 - loss: 24.7512
Epoch 24/30
1076/1076 - 0s - 432us/step - accuracy: 0.4011 - loss: 24.7512
Epoch 25/30
1076/1076 - 0s - 452us/step - accuracy: 0.4011 - loss: 24.7512
Epoch 26/30
1076/1076 - 0s - 457us/step - accuracy: 0.4010 - loss: 24.7511
Epoch 27/30
1076/1076 - 1s - 474us/step - accuracy: 0.4012 - loss: 24.7465
Epoch 28/30
1076/1076 - 0s - 428us/step - accuracy: 0.4008 - loss: 24.7493
Epoch 29/30
1076/1076 - 0s - 458us/step - accuracy: 0.3991 - loss: 24.7605
Epoch 30/30
1076/1076 - 0s - 429us/step - accuracy: 0.4000 - loss: 24.7643

In [47]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [48]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 330us/step
Pred        BASEL  BELGRADE
True
BASEL        2236      1446
BELGRADE     1082        10
BUDAPEST      214         0
DEBILT         82         0
DUSSELDORF     29         0
HEATHROW       82         0
KASSEL         11         0
LJUBLJANA      61         0
MAASTRICHT      9         0
MADRID        412        46
MUNCHENB        8         0
OSLO            5         0
STOCKHOLM       4         0
VALENTIA        1         0

Loss improved but accuracy remains low, let’s try adjusting layers

In [50]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='tanh')) # Options: sigmoid, tanh, softmax, relu

In [51]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 14, 16)         │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,951 (15.43 KB)

 Trainable params: 3,951 (15.43 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [53]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 649us/step - accuracy: 0.2093 - loss: 22.0966
Epoch 2/30
1076/1076 - 0s - 420us/step - accuracy: 0.2833 - loss: 25.9632
Epoch 3/30
1076/1076 - 0s - 418us/step - accuracy: 0.3239 - loss: 27.3189
Epoch 4/30
1076/1076 - 0s - 420us/step - accuracy: 0.5188 - loss: 24.9581
Epoch 5/30
1076/1076 - 0s - 417us/step - accuracy: 0.6116 - loss: 23.2070
Epoch 6/30
1076/1076 - 0s - 417us/step - accuracy: 0.6098 - loss: 22.6919
Epoch 7/30
1076/1076 - 0s - 418us/step - accuracy: 0.6092 - loss: 22.5851
Epoch 8/30
1076/1076 - 0s - 419us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 9/30
1076/1076 - 0s - 419us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 10/30
1076/1076 - 0s - 416us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 11/30
1076/1076 - 0s - 417us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 12/30
1076/1076 - 0s - 415us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 13/30
1076/1076 - 0s - 418us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 14/30
1076/1076 - 0s - 419us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 15/30
1076/1076 - 0s - 419us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 16/30
1076/1076 - 0s - 422us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 17/30
1076/1076 - 0s - 441us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 18/30
1076/1076 - 0s - 417us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 19/30
1076/1076 - 0s - 416us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 20/30
1076/1076 - 0s - 419us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 21/30
1076/1076 - 0s - 418us/step - accuracy: 0.6092 - loss: 22.5851
Epoch 22/30
1076/1076 - 0s - 416us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 23/30
1076/1076 - 0s - 418us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 24/30
1076/1076 - 0s - 418us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 25/30
1076/1076 - 0s - 434us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 26/30
1076/1076 - 0s - 420us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 27/30
1076/1076 - 0s - 418us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 28/30
1076/1076 - 0s - 419us/step - accuracy: 0.6092 - loss: 22.5851
Epoch 29/30
1076/1076 - 0s - 418us/step - accuracy: 0.6092 - loss: 22.5852
Epoch 30/30
1076/1076 - 0s - 433us/step - accuracy: 0.6092 - loss: 22.5852

In [54]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [55]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 314us/step
Pred        BASEL  BUDAPEST  DUSSELDORF  HEATHROW
True
BASEL        3451       216          12         3
BELGRADE     1092         0           0         0
BUDAPEST      214         0           0         0
DEBILT         82         0           0         0
DUSSELDORF     29         0           0         0
HEATHROW       82         0           0         0
KASSEL         11         0           0         0
LJUBLJANA      61         0           0         0
MAASTRICHT      9         0           0         0
MADRID        458         0           0         0
MUNCHENB        8         0           0         0
OSLO            5         0           0         0
STOCKHOLM       4         0           0         0
VALENTIA        1         0           0         0

Loss is now stable but still not as low as we’d like; however, accuracy is much higher. Let’s try sigmoid and relu.

In [57]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='sigmoid')) # Options: sigmoid, tanh, softmax, relu

In [58]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_4 (Conv1D)               │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 14, 16)         │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,951 (15.43 KB)

 Trainable params: 3,951 (15.43 KB)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [60]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 642us/step - accuracy: 0.6220 - loss: 10911.0840
Epoch 2/30
1076/1076 - 0s - 407us/step - accuracy: 0.6433 - loss: 112711.5312
Epoch 3/30
1076/1076 - 0s - 413us/step - accuracy: 0.6433 - loss: 358724.8438
Epoch 4/30
1076/1076 - 0s - 407us/step - accuracy: 0.6432 - loss: 818417.6875
Epoch 5/30
1076/1076 - 0s - 404us/step - accuracy: 0.6432 - loss: 1420243.5000
Epoch 6/30
1076/1076 - 0s - 404us/step - accuracy: 0.6433 - loss: 2297046.7500
Epoch 7/30
1076/1076 - 0s - 412us/step - accuracy: 0.6434 - loss: 3318957.7500
Epoch 8/30
1076/1076 - 0s - 410us/step - accuracy: 0.6434 - loss: 4703046.5000
Epoch 9/30
1076/1076 - 0s - 408us/step - accuracy: 0.6434 - loss: 6245169.0000
Epoch 10/30
1076/1076 - 0s - 406us/step - accuracy: 0.6434 - loss: 8038128.0000
Epoch 11/30
1076/1076 - 0s - 408us/step - accuracy: 0.6434 - loss: 10425247.0000
Epoch 12/30
1076/1076 - 0s - 409us/step - accuracy: 0.6434 - loss: 12806901.0000
Epoch 13/30
1076/1076 - 0s - 404us/step - accuracy: 0.6435 - loss: 15725423.0000
Epoch 14/30
1076/1076 - 0s - 406us/step - accuracy: 0.6435 - loss: 18907026.0000
Epoch 15/30
1076/1076 - 0s - 412us/step - accuracy: 0.6435 - loss: 22562026.0000
Epoch 16/30
1076/1076 - 0s - 403us/step - accuracy: 0.6435 - loss: 26785140.0000
Epoch 17/30
1076/1076 - 0s - 408us/step - accuracy: 0.6435 - loss: 31490098.0000
Epoch 18/30
1076/1076 - 0s - 413us/step - accuracy: 0.6436 - loss: 36268872.0000
Epoch 19/30
1076/1076 - 0s - 405us/step - accuracy: 0.6435 - loss: 41651416.0000
Epoch 20/30
1076/1076 - 0s - 405us/step - accuracy: 0.6436 - loss: 48007732.0000
Epoch 21/30
1076/1076 - 0s - 414us/step - accuracy: 0.6435 - loss: 54633648.0000
Epoch 22/30
1076/1076 - 0s - 440us/step - accuracy: 0.6436 - loss: 61573200.0000
Epoch 23/30
1076/1076 - 0s - 411us/step - accuracy: 0.6436 - loss: 69367880.0000
Epoch 24/30
1076/1076 - 0s - 416us/step - accuracy: 0.6437 - loss: 77360144.0000
Epoch 25/30
1076/1076 - 0s - 412us/step - accuracy: 0.6437 - loss: 86206960.0000
Epoch 26/30
1076/1076 - 0s - 411us/step - accuracy: 0.6437 - loss: 95729192.0000
Epoch 27/30
1076/1076 - 0s - 407us/step - accuracy: 0.6437 - loss: 105971800.0000
Epoch 28/30
1076/1076 - 0s - 410us/step - accuracy: 0.6437 - loss: 116968848.0000
Epoch 29/30
1076/1076 - 0s - 407us/step - accuracy: 0.6437 - loss: 128516488.0000
Epoch 30/30
1076/1076 - 0s - 410us/step - accuracy: 0.6437 - loss: 141078432.0000

In [61]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [62]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 327us/step
Pred        BASEL  VALENTIA
True
BASEL        3679         3
BELGRADE     1092         0
BUDAPEST      214         0
DEBILT         82         0
DUSSELDORF     29         0
HEATHROW       82         0
KASSEL         11         0
LJUBLJANA      61         0
MAASTRICHT      9         0
MADRID        458         0
MUNCHENB        8         0
OSLO            5         0
STOCKHOLM       4         0
VALENTIA        1         0